// showcase/examples/video-with-control-vuejs/src/App.vue
<template>
  <div id="app">
    <keep-alive>
      <Video
              :modal="true"
              :dataSource="dataSource"
              :options="{top: '50', left: '50'}"
              :showStats="true"
              :showTime="true"
              :frameRate=25
              class="video"
      >
      </Video>
    </keep-alive>
  </div>
</template>
<script>
    // @ is an alias to /src
    import Video from 'osh-vue/components/VideoWithControl.vue';
    import VideoOsh from "osh/datareceiver/Video.js";

    export default {
        components: {
            Video
        },
        data: function () {
            return {
                dataSource: null
            }
        },
        beforeMount() {
            // setup video
            // create data source for UAV camera
            this.dataSource = new VideoOsh("drone-Video", {
                protocol: 'ws',
                service: 'SOS',
                endpointUrl: 'sensiasoft.net:8181/sensorhub/sos',
                offeringID: 'urn:mysos:solo:video2',
                observedProperty: 'http://sensorml.com/ont/swe/property/VideoFrame',
                startTime: '2015-12-19T21:04:29.231Z',
                endTime: '2015-12-19T21:09:19.675Z',
                // endpointUrl: 'localhost:8082/sensorhub/sos',
                // offeringID: 'replay-android',
                // startTime: '2020-06-06T15:07:15.359Z',
                // endTime: '2020-06-06T15:07:57.016Z',
                replaySpeed: 1
            });
        }
    };
</script>
<style>
  body {
    overflow-x: hidden;
    margin: 0;
    padding:50px;
  }

  .video {
    width: 500px;
  }
</style>

// demos/3dr-solo-uav/3dr-solo-uav-react/src/App.js
import React from 'react';
import './App.css';
import BaseMap from "./components/BaseMap";
import {SoloVideoComponent} from "./components/SoloVideo";
import DataSynchronizer from "osh/core/timesync/DataSynchronizer";
import SosGetResult from "osh/core/datasource/sos/SosGetResult.datasource.js";
import {Mode} from "osh/core/datasource/Mode";

function App() {
    let START_TIME = '2015-12-19T21:04:29.231Z';
    let END_TIME = '2015-12-19T21:09:19.675Z';

    // create data source for Android phone GPS
    let platformLocationDataSource = new SosGetResult('android-GPS', {
        endpointUrl: 'sensiasoft.net:8181/sensorhub/sos',
        offeringID: 'urn:mysos:solo:nav2',
        observedProperty: 'http://www.opengis.net/def/property/OGC/0/PlatformLocation',
        startTime: START_TIME,
        endTime: END_TIME,
        mode: Mode.REPLAY
    });

    let platformOrientationDataSource = new SosGetResult('android-Heading', {
        endpointUrl: 'sensiasoft.net:8181/sensorhub/sos',
        offeringID: 'urn:mysos:solo:nav2',
        observedProperty: 'http://www.opengis.net/def/property/OGC/0/PlatformOrientation',
        startTime: START_TIME,
        endTime: END_TIME,
        mode: Mode.REPLAY
    });

    let gimbalOrientationDataSource = new SosGetResult('android-Heading', {
        endpointUrl: 'sensiasoft.net:8181/sensorhub/sos',
        offeringID: 'urn:mysos:solo:nav2',
        observedProperty: 'http://sensorml.com/ont/swe/property/OSH/0/GimbalOrientation',
        startTime: START_TIME,
        endTime: END_TIME,
        mode: Mode.REPLAY
    });

    // create data source for UAV camera
    let videoDataSource = new SosGetResult("drone-Video", {
        endpointUrl: 'sensiasoft.net:8181/sensorhub/sos',
        offeringID: 'urn:mysos:solo:video2',
        observedProperty: 'http://sensorml.com/ont/swe/property/VideoFrame',
        startTime: '2015-12-19T21:04:29.231Z',
        endTime: '2015-12-19T21:09:19.675Z',
        mode: Mode.REPLAY
    });

    const dataSynchronizer = new DataSynchronizer({
        masterTimeRefreshRate: 250,
        replaySpeed: 1.0,
        dataSources: [platformLocationDataSource, platformOrientationDataSource, gimbalOrientationDataSource, videoDataSource]
    });
  const component = (
    <div className="App">
      <SoloVideoComponent
          videoDataSource={videoDataSource}
      />
      <BaseMap
          platformLocationDataSource={platformLocationDataSource}
          platformOrientationDataSource={platformOrientationDataSource}
          gimbalOrientationDataSource={gimbalOrientationDataSource}
      />
    </div>
  );
    // start streaming
    dataSynchronizer.connect();
    return component;
}

export default App;
